---
# Disable swap (required by Kubernetes)

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    replace: ''

# Install required dependencies

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

# Install containerd (Kubernetes runtime)

- name: Install containerd
  apt:
    name: containerd
    state: present

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd config
  command: containerd config default
  register: containerd_config
  changed_when: false

- name: Write containerd config file
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: yes
    state: started

# Add Kubernetes official repository (NEW METHOD)

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes GPG key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    filename: kubernetes

# Install Kubernetes components

- name: Install kubelet, kubeadm, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes


