---
- name: Check if worker already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join worker to cluster
  command: "{{ hostvars[groups['master'][0]].kubeadm_join_cmd }}"
  when: not kubelet_conf.stat.exists
